spring:
  application:
    name: test
  redis:
#    host: localhost
#    port: 6379
    host: redis://srv-captain--vzumsidfqx-redis-6x
    port: 6379
    database: 0
    password: jT7VIJRxHpiYafd9
server:
  port: 8080
telegram:
  pttchatid: 878586374
  updatepassword: 123$zxcV
  groupchatid: -898857219
#heroku:
#  url: https://twkiz-1.herokuapp.com/
heroku:
  url: https://vzumsidfqx.us15.qoddiapp.com/
